version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: test_user
      DB_PASSWORD: test_password
      DB_NAME: test_db
    volumes:
      - ./src:/usr/src/app/src

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data